In [1]:
import pandas as pd
import numpy as np

In [20]:
one_list = []
for i in range(0,102):
    df = pd.read_html("https://en.wikipedia.org/wiki/List_of_Bollywood_films_of_"+str(1920+i),
                      match = "Director")
    
    if len(df)>1:
        k = []
        for j in range(0,len(df)):
            if "Original film" not in df[j].columns:
                if "No." not in df[j].columns:
                    if "Worldwide Gross" not in df[j].columns:
                        k.append(df[j])
        df = pd.concat(k,ignore_index = True,sort = False)
        if "Genre" not in df.columns:
            if "Music" not in df.columns:
                df['Music'] = np.NaN
                df['Genre'] = np.NaN
                df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
                df['year'] = 1920+i
                print(1920+i)
                print(df.columns)
        elif "Music Director" in df.columns:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music Director']]
            df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        elif "Music" not in df.columns:
            df['Music'] = np.NaN
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        elif "Genre" not in df.columns:
            df['Genre'] = np.NaN
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        else:
            try:
                df = df[['Title', 'Director', 'Cast','Genre', 'Music director']]
                df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
                df['year'] = 1920+i
                print(1920+i)
                print(df.columns)
            except:
                df = df[['Title', 'Director', 'Cast','Genre','Music']]
                df['year'] = 1920+i
                print(1920+i)
                print(df.columns)
    else:
        df = df[0]
        if "Music Director" in df.columns:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music Director']]
            df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        elif "Music" not in df.columns:
            df['Music'] = np.NaN
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        elif "Genre" not in df.columns:
            df['Genre'] = np.NaN
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 1920+i
            print(1920+i)
            print(df.columns)
        else:
            try:
                df = df[['Title', 'Director', 'Cast','Genre', 'Music director']]
                df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
                df['year'] = 1920+i
                print(1920+i)
                print(df.columns)
            except:
                df = df[['Title', 'Director', 'Cast','Genre','Music']]
                df['year'] = 1920+i
                print(1920+i)
                print(df.columns)
    one_list.append(df)

1920
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1921
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1922
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1923
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1924
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1925
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1926
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1927
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1928
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1929
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1930
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1931
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1932
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1933
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1934
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1935
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1936
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1937
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1938
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1939
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1940
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1941
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1942
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1943
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1944
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1945
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1946
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1947
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1948
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1949
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1950
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1951
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1952
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1953
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1954
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1955
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1956
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1957
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1958
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1959
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1960
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1961
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1962
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1963
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1964
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1965
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1966
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1967
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1968
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1969
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1970
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1971
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1972
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1973
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1974
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1975
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1976
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1977
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1978
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1979
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1980
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1981
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1982
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1983
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1984
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1985
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1986
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1987
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1988
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1989
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1990
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1991
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1992
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1993
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1994
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1995
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1996
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1997
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1998
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
1999
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2000
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2001
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2002
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2003
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2004
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2005
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2006
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2007
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2008
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2009
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2010
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2011
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2012
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2013
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2014
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2015
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2016
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2017
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')

2018
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2019
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2020
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')
2021
Index(['Title', 'Director', 'Cast', 'Genre', 'Music', 'year'], dtype='object')

In [22]:
bollywood = pd.concat(one_list,ignore_index = True,sort = False)

In [23]:
bollywood

,Title,Director,Cast,Genre,Music,year
0,Balika Badhu a.k.a. Baby Bride,P. T. Shaida (Tulsidutt Shaida),"Miss Ali, Tarak Bagcha, Pandit Tulsidutt Shaida",Social,NaN,1920
1,Daksha Yagna a.k.a. Sati Parvati,Vishnupant Divekar,"Khalil, Prabha, Vaidya",Mythology,NaN,1920
2,Jalandhar Vrinda a.k.a. Sati Tulsi Vrinda,G. V. Sane,NaN,Mythology,NaN,1920
3,Kansa Vadha a.k.a. End Of The Tyrant King,G. V. Sane,NaN,Mythology,NaN,1920
4,Katorabhar Khoon a.k.a.The Stinger Stung a.k.a...,S. N. Patankar,"Trymbakrao Pradhan, Tara Koregaonkar, Baba Vya...",Social,NaN,1920
...,...,...,...,...,...,...
10087,No Means No,Vikash Verma,Dhruv VermaGulshan GroverSylwia CzechSharad Ka...,NaN,NaN,2021
10088,Bhool Bhulaiyaa 2,Anees Bazmee,Kartik AaryanTabuKiara Advani,NaN,NaN,2021
10089,Tadap,Milan Luthria,Ahan ShettyTara Sutaria,NaN,NaN,2021
10090,Laal Singh Chaddha,Advait Chandan,Aamir KhanKareena Kapoor,NaN,NaN,2021
10091,Cirkus,Rohit Shetty,Ranveer SinghJacqueline FernandezPooja HegdeVa...,NaN,NaN,2021

In [24]:
bollywood = bollywood[bollywood['Title'].notna()]
bollywood = bollywood.reset_index(drop = True)

In [25]:
bollywood['language'] = "Hindi"
bollywood['industry'] = "Bollywood"

In [26]:
bollywood = bollywood.drop_duplicates()
bollywood = bollywood.reset_index(drop = True)

In [27]:
bollywood.to_csv("Bollywood_movies.csv",header =  True,index = False)

In [ ]:
bollywood.info()