In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1930
df1930s = pd.read_html("https://en.wikipedia.org/wiki/List_of_Telugu_films_of_the_1930s")
df1930s = df1930s[2]

In [3]:
df1930s.shape

(77, 7)

In [4]:
df1930s.columns

Index(['Title', 'Director', 'Production', 'Cast', 'Genre', 'Release',
       'Unnamed: 6'],
      dtype='object')

In [5]:
df1930s = df1930s[['Title', 'Director', 'Cast', 'Genre']]

In [6]:
df1930s["Music"] = np.NaN

In [7]:
df1930s['year'] = np.NaN

In [8]:
for i in range(0,len(df1930s)):
    if df1930s['Title'][i].isnumeric():
        a = df1930s['Title'][i]
    df1930s['year'][i] = a

/home/ug/anaconda3/envs/my_env/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [9]:
df1930s

,Title,Director,Cast,Genre,Music,year
0,1931,1931,1931,1931,NaN,1931.0
1,Kalidas,H. M. Reddy,"T. P. Rajalakshmi, P. G. Venkatesan, L. V. Prasad",Biographical,NaN,1931.0
2,1932,1932,1932,1932,NaN,1932.0
3,Bhakta Prahlada,H. M. Reddy,"Venkata Subbaiah Municipalle, Surabhi Kamalaba...",Devotional,NaN,1932.0
4,Rama Paduka Pattabhishekam,Sarvottam Badami,"C. S. R. Anjaneyulu, Surabhi Kamalabai, Yadava...",Devotional,NaN,1932.0
...,...,...,...,...,...,...
72,Radha Krishna,NaN,NaN,NaN,NaN,1939.0
73,Raithu Bidda,Gudavalli Ramabrahmam,"Bellary Raghava, P. Suri Babu, Suryakumari, G....",Social,NaN,1939.0
74,"Sri Venkateswara Mahatyam (Also Known as ""Bala...",P. Pullaiah,"C. S. R. Anjaneyulu, Santha Kumari, Rajeshwari...",Devotional,NaN,1939.0
75,Vande Mataram,B. N. Reddy,"Chittor V. Nagaiah, Kanchanamala, Lingamoorthy",Social,NaN,1939.0
76,Vara Vikrayam,C. Pullaiah,"Pushpavalli, Lakshmikantam Kavi, P. Bhanumathi...",Social,NaN,1939.0

In [10]:
# removing numerics from title columns
df1930s = df1930s[pd.to_numeric(df1930s['Title'], errors='coerce').isna()]
df1930s = df1930s.reset_index(drop = True)

In [11]:
one_list = []
for i in range(0,60):
    df = pd.read_html("https://en.wikipedia.org/wiki/List_of_Telugu_films_of_"+str(1940+i),
                      match = "Title")
    df = df[0]
    #if "Music" | "Music director" | "Music Director" not in df.columns:
     #   df["Music"] = np.NaN
    if "Genre" not in df.columns:
        df["Genre"] = np.NaN
    if "Music Director" in df.columns:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music Director']]
            df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
            df['year'] = 1940+i
    elif "Music" not in df.columns:
        df['Music'] = np.NaN
        df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
        df['year'] = 1940+i 
    else:
        try:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music director']]
            df.columns = ['Title', 'Director', 'Cast', 'Music']
            df['year'] = 1940+i
        except:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 1940+i
    one_list.append(df)

/home/ug/anaconda3/envs/my_env/lib/python3.7/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [12]:
df4099 = pd.concat(one_list,ignore_index = True, sort = False)

In [13]:
df4099

,Title,Director,Cast,Genre,Music,year
0,Barrister Parvateesarrn,R. Prakash,"Lanka Satyam, G. Varalakshmi, K. Sivarao, L. V...",Comedy,NaN,1940
1,Bhoja Kalidasu,H. V. Babu,"Adhanki Srirama Murthy, Parepalli Subba Rao, P...",Mythology,NaN,1940
2,Bhookailas,Sundar Rao Nadkarni,"M. V. Subbiah Naidu, R. Nagendra Rao, Lakshmi ...",Devotional,NaN,1940
3,Bondam Pelli,H. M. Reddy,"L. V. Prasad, G. Varalakshmi",Comedy,NaN,1940
4,Chaduvukunna Bharya,H. M. Reddy,"Lanka Satyam, G. Varalakshmi",Comedy,NaN,1940
...,...,...,...,...,...,...
2321,Telangana,NaN,"Suresh, Srihari, Indraja, Vinod Kumar",NaN,NaN,1999
2322,Veedu Samanyudu Kadhu,Uppalapati Narayana,"Prakash Raj, Raasi, Sanghavi",NaN,NaN,1999
2323,Velugu Needalu,Mourya,"Venkat, Meena, Brahmanandam",NaN,NaN,1999
2324,Vichitram,Jandhyala,"Gajjal Srinivas, Charmy Kaur, Brahmanandam",NaN,NaN,1999
2325,Yamajathakudu,Nimmala Shankar,"Mohan Babu, Sakshi Shivanand, Rajendra Prasad,...",NaN,NaN,1999

In [14]:
two_list = []
for i in range(0,20):
    df = pd.read_html("https://en.wikipedia.org/wiki/List_of_Telugu_films_of_"+str(2000+i),
                      match = "Title")
    #df = df[0]
    k = []
    for j in range(0,len(df)-1):
        if "Rank" not in df[j].columns:
            k.append(df[j])
    df = pd.concat(k,ignore_index = True,sort = False)
    if "Genre" not in df.columns:
        df["Genre"] = np.NaN
    if "Music Director" in df.columns:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music Director']]
            df.columns = ['Title', 'Director', 'Cast','Genre', 'Music']
            df['year'] = 2000+i
    elif "Music" not in df.columns:
        df['Music'] = np.NaN
        df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
        df['year'] = 2000+i 
    else:
        try:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music director']]
            df.columns = ['Title', 'Director', 'Cast', 'Music']
            df['year'] = 2000+i
        except:
            df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
            df['year'] = 2000+i
    two_list.append(df)

In [15]:
df0019 = pd.concat(two_list,ignore_index = True, sort = False)

In [16]:
df0019

,Title,Director,Cast,Genre,Music,year
0,Kodanda Ramudu,NaN,"J. D. Chakravarthi, Saptaparna Saha, Rambha, Laya",Drama,NaN,2000
1,Annayya,NaN,"Chiranjeevi, Ravi Teja, Soundarya, Simran, Sha...",Drama / Action,NaN,2000
2,Postman,NaN,"Mohan Babu, Soundarya, Raasi",Romance,NaN,2000
3,Vamsoddharakudu,NaN,"Balakrishna Nandamuri, Sakshi Shivanand, Ramya...",Action,NaN,2000
4,Kalisundam Raa,NaN,"Venkatesh, Simran",Drama,NaN,2000
...,...,...,...,...,...,...
1977,Ruler,K. S. Ravikumar,"Nandamuri Balakrishna, Sonal Chauhan, Vedhika,...",NaN,NaN,2019
1978,Prati Roju Pandage,Maruthi Dasari,"Sai Dharam Tej, Raashi Khanna, Sathyaraj, Rao ...",NaN,NaN,2019
1979,Iddari Lokam Okate,G. R. Krishna,"Raj Tarun, Shalini Pandey, Nassar, Master Bharath",NaN,NaN,2019
1980,Mathu Vadalara,Ritesh Rana,"Sri Simha, Naresh Agastya, Athulya Chandra, Ve...",NaN,NaN,2019
1981,Software Sudheer,P. Rajasekhar Reddy,"Sudigali Sudheer, Dhanya Balakrishna, Nassar, ...",NaN,NaN,2019

In [17]:
three_list = []
for i in range(0,2):
    df = pd.read_html("https://en.wikipedia.org/wiki/List_of_Telugu_films_of_"+str(2020+i),
                      match = "Title")
    k = []
    for j in range(0,len(df)):
        if "Rank" not in df[j].columns:
            k.append(df[j])
    df = pd.concat(k,ignore_index = True,sort = False)
    if "Music" not in df.columns:
        df['Music'] = np.NaN
    if "Genre" not in df.columns:
        df["Genre"] = np.NaN
        
    df = df[['Title', 'Director', 'Cast','Genre', 'Music']]
    df['year'] = 2020+i
    three_list.append(df)

In [18]:
df2021 = pd.concat(three_list,ignore_index = True, sort = False)

In [19]:
df2021

,Title,Director,Cast,Genre,Music,year
0,Beautiful,Agasthya Manju,Parth SuriNaina Ganguly,NaN,NaN,2020
1,Oollalla Oollalla,Satya Prakash,NatarajNoorin ShereefAnkeeta R Maharanaa,NaN,NaN,2020
2,Utthara,SR Thirupathi,SreeramKarronya KatrynnAjay Ghosh,NaN,NaN,2020
3,"Wife,i",GSSP Kalyan,Abhishek ReddySakshi SidiyaKavya,NaN,NaN,2020
4,Sarileru Neekevvaru,Anil Ravipudi,Mahesh BabuRashmika MandannaVijayashantiPrakas...,NaN,NaN,2020
...,...,...,...,...,...,...
143,RRR,S. S. Rajamouli,N. T. Rama Rao JrRam CharanAlia BhattOlivia Mo...,NaN,NaN,2021
144,Maha Samudram,Ajay Bhupathi,SharwanandSiddharthAditi Rao HydariAnu Emmanue...,NaN,NaN,2021
145,Ghani,Kiran Korrapati,Varun TejSaiee ManjrekarUpendraSuniel ShettyJa...,NaN,NaN,2021
146,Pushpa: The Rise,Sukumar,Allu ArjunRashmika MandannaFahadh FaasilJagapa...,NaN,NaN,2021
147,Agent,Surender Reddy,Akhil AkkineniSakshi Vaidya,NaN,NaN,2021

In [20]:
final_list = [df1930s,df4099,df0019,df2021]

In [21]:
tollywood = pd.concat(final_list,ignore_index = True, sort = False)

In [22]:
tollywood = tollywood[tollywood['Title'].notna()]
tollywood = tollywood.reset_index(drop = True)

In [23]:
tollywood.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4470 entries, 0 to 4469
Data columns (total 6 columns):
Title       4470 non-null object
Director    4253 non-null object
Cast        4337 non-null object
Genre       2931 non-null object
Music       788 non-null object
year        4470 non-null float64
dtypes: float64(1), object(5)
memory usage: 209.7+ KB

In [24]:
tollywood['language'] = "Telugu"
tollywood['industry'] = "Tollywood"

In [25]:
tollywood = tollywood.drop_duplicates()
tollywood = tollywood.reset_index(drop = True)

In [26]:
tollywood.to_csv("Tollywood_movies.csv",header =  True,index = False)

In [27]:
#pip install tmdbv3api

In [28]:
from tmdbv3api import TMDb

In [30]:
import json
import requests
tmdb = TMDb()
tmdb.api_key = '44a7f191999915b9937fd53ce2d98921'

In [72]:
from tmdbv3api import Movie
tmdb_movie = Movie()
def get_genre(x): # x is the title of the movie
    genres = []
    # search movie
    result = tmdb_movie.search(x)
    if len(result) != 0:
        movie_id = result[0].id
        response = requests.get('https://api.themoviedb.org/3/movie/{}?api_key={}'.format(movie_id,tmdb.api_key))
        data_json = response.json()
        if data_json['genres']:
            genre_str = ""
            for i in range(0,len(data_json['genres'])):
                genres.append(data_json['genres'][i]['name'])
            return genre_str.join(genres)
        else:
            np.NaN
    else:
        np.NaN

In [74]:
#tollywood['Get_genre'] = tollywood['Title'].apply(lambda x: get_genre(str(x)))

KeyboardInterrupt: